---
name: build asl-update-node-list
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - codename: bookworm
          - codename: bullseye
          - codename: buster
    steps:
      - uses: actions/checkout@v2

      - run: |
          mkdir docker-build
          cat <<EOF > docker-build/Dockerfile
          FROM debian:${{ matrix.codename }}
          RUN apt-get update && apt-get install -y debhelper devscripts
          VOLUME /asl-update-node-list
          WORKDIR /asl-update-node-list/asl-update-node-list
          CMD ["debuild", "-b", "-uc", "-us"]
          EOF

      - name: Build deb
        run: |
          cd docker-build
          docker build -t asl-update-node-list .
          docker run --rm -v $(pwd)/../../:/asl-update-node-list asl-update-node-list
          cd ..
          mv ../*.deb ../*.build ../*.buildinfo ../*.changes .

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: asl-update-node-list-${{ matrix.codename }}
          path: |
            *.deb
            *.build
            *.buildinfo
            *.changes
